/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'other' : IDL.Null,
  'candy' : IDL.Null,
  'cake' : IDL.Null,
  'glucose' : IDL.Null,
  'toffee' : IDL.Null,
  'chocolate' : IDL.Null,
});
export const Sweet = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'image' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SweetShopReview = IDL.Record({
  'reviewText' : IDL.Opt(IDL.Text),
  'author' : IDL.Principal,
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSweet' : IDL.Func([Sweet], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllReviews' : IDL.Func([], [IDL.Vec(SweetShopReview)], ['query']),
  'getAllSweets' : IDL.Func([], [IDL.Vec(Sweet)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReview' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'updateSweetPrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'other' : IDL.Null,
    'candy' : IDL.Null,
    'cake' : IDL.Null,
    'glucose' : IDL.Null,
    'toffee' : IDL.Null,
    'chocolate' : IDL.Null,
  });
  const Sweet = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'image' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SweetShopReview = IDL.Record({
    'reviewText' : IDL.Opt(IDL.Text),
    'author' : IDL.Principal,
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSweet' : IDL.Func([Sweet], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllReviews' : IDL.Func([], [IDL.Vec(SweetShopReview)], ['query']),
    'getAllSweets' : IDL.Func([], [IDL.Vec(Sweet)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReview' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'updateSweetPrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };